name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          base: header, activity, repositories

          repositories: yes

          plugin_repositories: yes

          plugin_repositories_limit: 100

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 30
